/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cotizacion } from '../../models/cotizacion';
import { CotizacionInput } from '../../models/cotizacion-input';

export interface CreateCotizacion$Params {
      body: CotizacionInput
}

export function createCotizacion(http: HttpClient, rootUrl: string, params: CreateCotizacion$Params, context?: HttpContext): Observable<StrictHttpResponse<Cotizacion>> {
  const rb = new RequestBuilder(rootUrl, createCotizacion.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cotizacion>;
    })
  );
}

createCotizacion.PATH = '/api/cotizaciones';
