/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cotizacion } from '../../models/cotizacion';

export interface GetCotizacionById$Params {

/**
 * ID of cotizacion to return
 */
  id: number;
}

export function getCotizacionById(http: HttpClient, rootUrl: string, params: GetCotizacionById$Params, context?: HttpContext): Observable<StrictHttpResponse<Cotizacion>> {
  const rb = new RequestBuilder(rootUrl, getCotizacionById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cotizacion>;
    })
  );
}

getCotizacionById.PATH = '/api/cotizaciones/{id}';
