/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SuggestMaterials$Params {
      body: {

/**
 * ID of the solicitud for which to suggest materials
 */
'id_solicitud': number;
}
}

export function suggestMaterials(http: HttpClient, rootUrl: string, params: SuggestMaterials$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
'solicitud_id'?: number;
'suggestions'?: Array<{
'material_name'?: string;
'quantity'?: number;
'unit'?: string;
'notes'?: string;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, suggestMaterials.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message'?: string;
      'solicitud_id'?: number;
      'suggestions'?: Array<{
      'material_name'?: string;
      'quantity'?: number;
      'unit'?: string;
      'notes'?: string;
      }>;
      }>;
    })
  );
}

suggestMaterials.PATH = '/api/cotizaciones/suggest-materials';
