/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Visita } from '../../models/visita';
import { VisitaInput } from '../../models/visita-input';

export interface CreateVisita$Params {
      body: VisitaInput
}

export function createVisita(http: HttpClient, rootUrl: string, params: CreateVisita$Params, context?: HttpContext): Observable<StrictHttpResponse<Visita>> {
  const rb = new RequestBuilder(rootUrl, createVisita.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Visita>;
    })
  );
}

createVisita.PATH = '/api/visitas';
