/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Visita } from '../../models/visita';

export interface GetVisitaById$Params {

/**
 * ID of visita to return
 */
  id: number;
}

export function getVisitaById(http: HttpClient, rootUrl: string, params: GetVisitaById$Params, context?: HttpContext): Observable<StrictHttpResponse<Visita>> {
  const rb = new RequestBuilder(rootUrl, getVisitaById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Visita>;
    })
  );
}

getVisitaById.PATH = '/api/visitas/{id}';
