/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Visita } from '../../models/visita';

export interface GetVisitas$Params {
}

export function getVisitas(http: HttpClient, rootUrl: string, params?: GetVisitas$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Visita>>> {
  const rb = new RequestBuilder(rootUrl, getVisitas.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Visita>>;
    })
  );
}

getVisitas.PATH = '/api/visitas';
