/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Empleado } from '../../models/empleado';
import { EmpleadoInput } from '../../models/empleado-input';

export interface CreateEmpleado$Params {
      body: EmpleadoInput
}

export function createEmpleado(http: HttpClient, rootUrl: string, params: CreateEmpleado$Params, context?: HttpContext): Observable<StrictHttpResponse<Empleado>> {
  const rb = new RequestBuilder(rootUrl, createEmpleado.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Empleado>;
    })
  );
}

createEmpleado.PATH = '/api/empleados';
