/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Empleado } from '../../models/empleado';
import { EmpleadoInput } from '../../models/empleado-input';

export interface UpdateEmpleado$Params {

/**
 * ID of empleado to update
 */
  id: number;
      body: EmpleadoInput
}

export function updateEmpleado(http: HttpClient, rootUrl: string, params: UpdateEmpleado$Params, context?: HttpContext): Observable<StrictHttpResponse<Empleado>> {
  const rb = new RequestBuilder(rootUrl, updateEmpleado.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Empleado>;
    })
  );
}

updateEmpleado.PATH = '/api/empleados/{id}';
