/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Material } from '../../models/material';

export interface GetMateriales$Params {
}

export function getMateriales(http: HttpClient, rootUrl: string, params?: GetMateriales$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Material>>> {
  const rb = new RequestBuilder(rootUrl, getMateriales.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Material>>;
    })
  );
}

getMateriales.PATH = '/api/materiales';
