/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Cliente } from './models/cliente';
export type { ClienteInput } from './models/cliente-input';
export type { Cotizacion } from './models/cotizacion';
export type { CotizacionInput } from './models/cotizacion-input';
export type { DetalleSolicitud } from './models/detalle-solicitud';
export type { DetalleSolicitudInput } from './models/detalle-solicitud-input';
export type { Empleado } from './models/empleado';
export type { EmpleadoInput } from './models/empleado-input';
export type { Material } from './models/material';
export type { MaterialInput } from './models/material-input';
export type { Pago } from './models/pago';
export type { PagoInput } from './models/pago-input';
export type { Proyecto } from './models/proyecto';
export type { ProyectoInput } from './models/proyecto-input';
export type { Solicitud } from './models/solicitud';
export type { SolicitudInput } from './models/solicitud-input';
export type { Visita } from './models/visita';
export type { VisitaInput } from './models/visita-input';
