/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Proyecto } from '../../models/proyecto';
import { ProyectoInput } from '../../models/proyecto-input';

export interface CreateProyecto$Params {
      body: ProyectoInput
}

export function createProyecto(http: HttpClient, rootUrl: string, params: CreateProyecto$Params, context?: HttpContext): Observable<StrictHttpResponse<Proyecto>> {
  const rb = new RequestBuilder(rootUrl, createProyecto.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Proyecto>;
    })
  );
}

createProyecto.PATH = '/api/proyectos';
