/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Proyecto } from '../../models/proyecto';

export interface GetProyectos$Params {
}

export function getProyectos(http: HttpClient, rootUrl: string, params?: GetProyectos$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Proyecto>>> {
  const rb = new RequestBuilder(rootUrl, getProyectos.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Proyecto>>;
    })
  );
}

getProyectos.PATH = '/api/proyectos';
