/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Proyecto } from '../../models/proyecto';

export interface GetProyectoById$Params {

/**
 * ID of proyecto to return
 */
  id: number;
}

export function getProyectoById(http: HttpClient, rootUrl: string, params: GetProyectoById$Params, context?: HttpContext): Observable<StrictHttpResponse<Proyecto>> {
  const rb = new RequestBuilder(rootUrl, getProyectoById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Proyecto>;
    })
  );
}

getProyectoById.PATH = '/api/proyectos/{id}';
