/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClienteInput {

  /**
   * Correo electrónico del cliente (opcional, debe ser único)
   */
  correo?: string;

  /**
   * Domicilio del cliente (opcional)
   */
  domicilio?: string;

  /**
   * Nombre del cliente
   */
  nombre: string;

  /**
   * Contraseña del cliente (min 8 caracteres)
   */
  password: string;

  /**
   * Número de teléfono (opcional)
   */
  telefono?: string;

  /**
   * Nombre de usuario (opcional)
   */
  usuario?: string;
}
