/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cliente {

  /**
   * Correo electronico del cliente
   */
  correo?: string;

  /**
   * Fecha de creacion
   */
  created_at?: string;

  /**
   * Domicilio del cliente
   */
  domicilio?: string;

  /**
   * ID unico del cliente
   */
  id_cliente?: string;

  /**
   * Nombre del cliente
   */
  nombre: string;

  /**
   * Numero de telefono
   */
  telefono?: string;

  /**
   * Fecha de actualizacion
   */
  updated_at?: string;

  /**
   * Nombre de usuario
   */
  usuario?: string;
}
