/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cotizacion {

  /**
   * Costo total de la cotización
   */
  costo_total: number;

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * Fecha de la cotización
   */
  fecha_cot?: string;

  /**
   * ID de la cotización
   */
  id_cotizacion?: number;

  /**
   * ID de la solicitud asociada
   */
  id_solicitud: number;

  /**
   * Notas adicionales de la cotización
   */
  notas?: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
