/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CotizacionInput {

  /**
   * Costo total de la cotización
   */
  costo_total: number;

  /**
   * ID de la solicitud asociada
   */
  id_solicitud: number;

  /**
   * Notas adicionales de la cotización
   */
  notas?: string;
}
