/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DetalleSolicitudInput {

  /**
   * Descripción del elemento
   */
  descripcion?: string;

  /**
   * ID de la solicitud a la que pertenece este detalle
   */
  id_solicitud: number;

  /**
   * Medida de alto
   */
  med_alt?: number;

  /**
   * Medida de ancho
   */
  med_anc?: number;
}
