/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DetalleSolicitud {

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * Descripción del elemento
   */
  descripcion?: string;

  /**
   * ID del detalle de solicitud
   */
  id_detalles?: number;

  /**
   * ID de la solicitud a la que pertenece este detalle
   */
  id_solicitud: number;

  /**
   * Medida de alto
   */
  med_alt?: number;

  /**
   * Medida de ancho
   */
  med_anc?: number;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
