/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmpleadoInput {

  /**
   * Correo electrónico
   */
  correo?: string;

  /**
   * Nombre del empleado
   */
  nombre: string;

  /**
   * Contraseña (si el empleado puede iniciar sesión)
   */
  password?: string;

  /**
   * Rol del empleado (e.g., admin, herrero)
   */
  rol?: string;

  /**
   * Número de teléfono
   */
  telefono?: string;
}
