/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Empleado {

  /**
   * Correo electrónico
   */
  correo?: string;

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * ID del empleado
   */
  id_empleado?: number;

  /**
   * Nombre del empleado
   */
  nombre: string;

  /**
   * Rol del empleado (e.g., admin, herrero)
   */
  rol?: string;

  /**
   * Número de teléfono
   */
  telefono?: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
