/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Material {

  /**
   * Costo por unidad del material
   */
  costo_unitario: number;

  /**
   * Fecha de creacion
   */
  created_at?: string;

  /**
   * ID unico del material
   */
  id_material?: number;

  /**
   * Nombre del material
   */
  nombre: string;

  /**
   * Cantidad en stock
   */
  stock: number;

  /**
   * Fecha de actualizacion
   */
  updated_at?: string;
}
