/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MaterialInput {

  /**
   * Costo por unidad del material
   */
  costo_unitario: number;

  /**
   * Nombre del material
   */
  nombre: string;

  /**
   * Cantidad en stock
   */
  stock: number;
}
