/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PagoInput {

  /**
   * Monto del pago
   */
  cantidad: number;

  /**
   * ID de la cotización asociada
   */
  id_cot: number;

  /**
   * Método de pago
   */
  metodo: string;
}
