/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Pago {

  /**
   * Monto del pago
   */
  cantidad: number;

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * Fecha del pago
   */
  fec_pago?: string;

  /**
   * ID de la cotización asociada
   */
  id_cot: number;

  /**
   * ID del pago
   */
  id_pago?: number;

  /**
   * Método de pago
   */
  metodo: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
