/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Proyecto {

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * ID del cliente asociado
   */
  id_cliente?: string;

  /**
   * ID del proyecto
   */
  id_proyecto?: number;

  /**
   * Observaciones del proyecto
   */
  observaciones?: string;

  /**
   * JSON del plano
   */
  plano_json?: {
};

  /**
   * URL del plano
   */
  plano_url?: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
