/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProyectoInput {

  /**
   * ID del cliente asociado
   */
  id_cliente?: string;

  /**
   * Observaciones del proyecto
   */
  observaciones?: string;

  /**
   * JSON del plano
   */
  plano_json?: {
};

  /**
   * URL del plano
   */
  plano_url?: string;
}
