/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Solicitud {

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * Descripción del proyecto
   */
  descripcion?: string;

  /**
   * Días disponibles del cliente
   */
  dias_disponibles?: string;

  /**
   * Dirección del trabajo
   */
  direccion: string;

  /**
   * Fecha de creación de la solicitud
   */
  fecha?: string;

  /**
   * Fecha y hora de la cita
   */
  fecha_cita?: string;

  /**
   * ID del cliente que hace la solicitud
   */
  id_cliente?: string;

  /**
   * ID de la solicitud
   */
  id_solicitud?: number;

  /**
   * Materiales sugeridos
   */
  materiales?: string;

  /**
   * Tipo de proyecto
   */
  tipo_proyecto?: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
