/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SolicitudInput {

  /**
   * Descripción del proyecto
   */
  descripcion?: string;

  /**
   * Días disponibles del cliente
   */
  dias_disponibles?: string;

  /**
   * Dirección del trabajo
   */
  direccion: string;

  /**
   * Fecha y hora de la cita
   */
  fecha_cita?: string;

  /**
   * ID del cliente que hace la solicitud
   */
  id_cliente?: string;

  /**
   * Materiales sugeridos
   */
  materiales?: string;

  /**
   * Tipo de proyecto
   */
  tipo_proyecto?: string;
}
