/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Visita {

  /**
   * Fecha de creación
   */
  created_at?: string;

  /**
   * Fecha y hora de la visita
   */
  fecha: string;

  /**
   * ID del empleado que realiza la visita
   */
  id_empleado: number;

  /**
   * ID de la solicitud visitada
   */
  id_solicitud: number;

  /**
   * ID de la visita
   */
  id_visita?: number;

  /**
   * Observaciones de la visita
   */
  observaciones?: string;

  /**
   * Fecha de actualización
   */
  updated_at?: string;
}
