/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VisitaInput {

  /**
   * Fecha y hora de la visita
   */
  fecha: string;

  /**
   * ID del empleado que realiza la visita
   */
  id_empleado: number;

  /**
   * ID de la solicitud visitada
   */
  id_solicitud: number;

  /**
   * Observaciones de la visita
   */
  observaciones?: string;
}
