/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cliente } from '../../models/cliente';
import { ClienteInput } from '../../models/cliente-input';

export interface CreateCliente$Params {
      body: ClienteInput
}

export function createCliente(http: HttpClient, rootUrl: string, params: CreateCliente$Params, context?: HttpContext): Observable<StrictHttpResponse<Cliente>> {
  const rb = new RequestBuilder(rootUrl, createCliente.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cliente>;
    })
  );
}

createCliente.PATH = '/api/clientes';
