/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cliente } from '../../models/cliente';

export interface GetClientes$Params {
}

export function getClientes(http: HttpClient, rootUrl: string, params?: GetClientes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Cliente>>> {
  const rb = new RequestBuilder(rootUrl, getClientes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Cliente>>;
    })
  );
}

getClientes.PATH = '/api/clientes';
