/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetalleSolicitud } from '../../models/detalle-solicitud';
import { DetalleSolicitudInput } from '../../models/detalle-solicitud-input';

export interface CreateDetalleSolicitud$Params {
      body: DetalleSolicitudInput
}

export function createDetalleSolicitud(http: HttpClient, rootUrl: string, params: CreateDetalleSolicitud$Params, context?: HttpContext): Observable<StrictHttpResponse<DetalleSolicitud>> {
  const rb = new RequestBuilder(rootUrl, createDetalleSolicitud.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DetalleSolicitud>;
    })
  );
}

createDetalleSolicitud.PATH = '/api/detalles-solicitud';
