/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetalleSolicitud } from '../../models/detalle-solicitud';

export interface GetDetallesSolicitud$Params {
}

export function getDetallesSolicitud(http: HttpClient, rootUrl: string, params?: GetDetallesSolicitud$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DetalleSolicitud>>> {
  const rb = new RequestBuilder(rootUrl, getDetallesSolicitud.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DetalleSolicitud>>;
    })
  );
}

getDetallesSolicitud.PATH = '/api/detalles-solicitud';
