/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetalleSolicitud } from '../../models/detalle-solicitud';

export interface GetDetalleSolicitudById$Params {

/**
 * ID of detalle solicitud to return
 */
  id: number;
}

export function getDetalleSolicitudById(http: HttpClient, rootUrl: string, params: GetDetalleSolicitudById$Params, context?: HttpContext): Observable<StrictHttpResponse<DetalleSolicitud>> {
  const rb = new RequestBuilder(rootUrl, getDetalleSolicitudById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DetalleSolicitud>;
    })
  );
}

getDetalleSolicitudById.PATH = '/api/detalles-solicitud/{id}';
