/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetalleSolicitud } from '../../models/detalle-solicitud';
import { DetalleSolicitudInput } from '../../models/detalle-solicitud-input';

export interface UpdateDetalleSolicitud$Params {

/**
 * ID of detalle solicitud to update
 */
  id: number;
      body: DetalleSolicitudInput
}

export function updateDetalleSolicitud(http: HttpClient, rootUrl: string, params: UpdateDetalleSolicitud$Params, context?: HttpContext): Observable<StrictHttpResponse<DetalleSolicitud>> {
  const rb = new RequestBuilder(rootUrl, updateDetalleSolicitud.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DetalleSolicitud>;
    })
  );
}

updateDetalleSolicitud.PATH = '/api/detalles-solicitud/{id}';
