/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Solicitud } from '../../models/solicitud';
import { SolicitudInput } from '../../models/solicitud-input';

export interface CreateSolicitud$Params {
      body: SolicitudInput
}

export function createSolicitud(http: HttpClient, rootUrl: string, params: CreateSolicitud$Params, context?: HttpContext): Observable<StrictHttpResponse<Solicitud>> {
  const rb = new RequestBuilder(rootUrl, createSolicitud.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Solicitud>;
    })
  );
}

createSolicitud.PATH = '/api/solicitudes';
