/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Solicitud } from '../../models/solicitud';

export interface GetSolicitudes$Params {
}

export function getSolicitudes(http: HttpClient, rootUrl: string, params?: GetSolicitudes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Solicitud>>> {
  const rb = new RequestBuilder(rootUrl, getSolicitudes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Solicitud>>;
    })
  );
}

getSolicitudes.PATH = '/api/solicitudes';
