/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Solicitud } from '../../models/solicitud';

export interface GetSolicitudById$Params {

/**
 * ID of solicitud to return
 */
  id: number;
}

export function getSolicitudById(http: HttpClient, rootUrl: string, params: GetSolicitudById$Params, context?: HttpContext): Observable<StrictHttpResponse<Solicitud>> {
  const rb = new RequestBuilder(rootUrl, getSolicitudById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Solicitud>;
    })
  );
}

getSolicitudById.PATH = '/api/solicitudes/{id}';
