/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pago } from '../../models/pago';
import { PagoInput } from '../../models/pago-input';

export interface CreatePago$Params {
      body: PagoInput
}

export function createPago(http: HttpClient, rootUrl: string, params: CreatePago$Params, context?: HttpContext): Observable<StrictHttpResponse<Pago>> {
  const rb = new RequestBuilder(rootUrl, createPago.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pago>;
    })
  );
}

createPago.PATH = '/api/pagos';
